name: trait-extract
channels:
  - defaults
dependencies:
  - gdal=3.8.3
  - geocube=0.4.2
  - geopandas=0.14.2
  - matplotlib=3.8.0
  - numpy=1.26.3
  - pandas=2.1.4
  - pyproj=3.6.1
  - python=3.12
  - rasterio=1.3.9
  - rioxarray=0.15
  - shapely=2.0.2
