{\rtf1\ansi\ansicpg1252\cocoartf2820
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\csgray\c0\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs20 \cf2 \cb3 \CocoaLigature0 name: trait-extract\
channels:\
  - defaults\
dependencies:\
  - geocube=0.4.2\
  - geopandas=0.14.2\
  - matplotlib=3.8.0\
  - numpy=1.26.3\
  - pandas=2.1.4\
  - pyproj=3.6.1\
  - python=3.12\
  - rasterio=1.3.9\
  - rioxarray=0.15\
  - shapely=2.0.2}